// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ghostcloud/ghostcloud/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetDeploymentRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryGetDeploymentRequest) Reset()         { *m = QueryGetDeploymentRequest{} }
func (m *QueryGetDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeploymentRequest) ProtoMessage()    {}
func (*QueryGetDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{2}
}
func (m *QueryGetDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeploymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeploymentRequest.Merge(m, src)
}
func (m *QueryGetDeploymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeploymentRequest proto.InternalMessageInfo

func (m *QueryGetDeploymentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryGetDeploymentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryGetDeploymentResponse struct {
	DeploymentMeta DeploymentMeta `protobuf:"bytes,1,opt,name=deploymentMeta,proto3" json:"deploymentMeta"`
	FileMeta       []*FileMeta    `protobuf:"bytes,2,rep,name=fileMeta,proto3" json:"fileMeta,omitempty"`
}

func (m *QueryGetDeploymentResponse) Reset()         { *m = QueryGetDeploymentResponse{} }
func (m *QueryGetDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeploymentResponse) ProtoMessage()    {}
func (*QueryGetDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{3}
}
func (m *QueryGetDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeploymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeploymentResponse.Merge(m, src)
}
func (m *QueryGetDeploymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeploymentResponse proto.InternalMessageInfo

func (m *QueryGetDeploymentResponse) GetDeploymentMeta() DeploymentMeta {
	if m != nil {
		return m.DeploymentMeta
	}
	return DeploymentMeta{}
}

func (m *QueryGetDeploymentResponse) GetFileMeta() []*FileMeta {
	if m != nil {
		return m.FileMeta
	}
	return nil
}

type QueryAllDeploymentMetaRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDeploymentMetaRequest) Reset()         { *m = QueryAllDeploymentMetaRequest{} }
func (m *QueryAllDeploymentMetaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDeploymentMetaRequest) ProtoMessage()    {}
func (*QueryAllDeploymentMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{4}
}
func (m *QueryAllDeploymentMetaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDeploymentMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDeploymentMetaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDeploymentMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDeploymentMetaRequest.Merge(m, src)
}
func (m *QueryAllDeploymentMetaRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDeploymentMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDeploymentMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDeploymentMetaRequest proto.InternalMessageInfo

func (m *QueryAllDeploymentMetaRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDeploymentMetaResponse struct {
	DeploymentMeta []DeploymentMeta    `protobuf:"bytes,1,rep,name=deploymentMeta,proto3" json:"deploymentMeta"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDeploymentMetaResponse) Reset()         { *m = QueryAllDeploymentMetaResponse{} }
func (m *QueryAllDeploymentMetaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDeploymentMetaResponse) ProtoMessage()    {}
func (*QueryAllDeploymentMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{5}
}
func (m *QueryAllDeploymentMetaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDeploymentMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDeploymentMetaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDeploymentMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDeploymentMetaResponse.Merge(m, src)
}
func (m *QueryAllDeploymentMetaResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDeploymentMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDeploymentMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDeploymentMetaResponse proto.InternalMessageInfo

func (m *QueryAllDeploymentMetaResponse) GetDeploymentMeta() []DeploymentMeta {
	if m != nil {
		return m.DeploymentMeta
	}
	return nil
}

func (m *QueryAllDeploymentMetaResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryDeploymentFileNamesRequest struct {
	Creator    string             `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SiteName   string             `protobuf:"bytes,2,opt,name=siteName,proto3" json:"siteName,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDeploymentFileNamesRequest) Reset()         { *m = QueryDeploymentFileNamesRequest{} }
func (m *QueryDeploymentFileNamesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDeploymentFileNamesRequest) ProtoMessage()    {}
func (*QueryDeploymentFileNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{6}
}
func (m *QueryDeploymentFileNamesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDeploymentFileNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDeploymentFileNamesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDeploymentFileNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeploymentFileNamesRequest.Merge(m, src)
}
func (m *QueryDeploymentFileNamesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDeploymentFileNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeploymentFileNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeploymentFileNamesRequest proto.InternalMessageInfo

func (m *QueryDeploymentFileNamesRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryDeploymentFileNamesRequest) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *QueryDeploymentFileNamesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryDeploymentFileNamesResponse struct {
	Meta       []*FileMeta         `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDeploymentFileNamesResponse) Reset()         { *m = QueryDeploymentFileNamesResponse{} }
func (m *QueryDeploymentFileNamesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDeploymentFileNamesResponse) ProtoMessage()    {}
func (*QueryDeploymentFileNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{7}
}
func (m *QueryDeploymentFileNamesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDeploymentFileNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDeploymentFileNamesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDeploymentFileNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeploymentFileNamesResponse.Merge(m, src)
}
func (m *QueryDeploymentFileNamesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDeploymentFileNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeploymentFileNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeploymentFileNamesResponse proto.InternalMessageInfo

func (m *QueryDeploymentFileNamesResponse) GetMeta() []*FileMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *QueryDeploymentFileNamesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDeploymentFileContentRequest struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SiteName string `protobuf:"bytes,2,opt,name=siteName,proto3" json:"siteName,omitempty"`
	FileName string `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (m *QueryGetDeploymentFileContentRequest) Reset()         { *m = QueryGetDeploymentFileContentRequest{} }
func (m *QueryGetDeploymentFileContentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeploymentFileContentRequest) ProtoMessage()    {}
func (*QueryGetDeploymentFileContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eaa93c58141bbd6, []int{8}
}
func (m *QueryGetDeploymentFileContentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeploymentFileContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeploymentFileContentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeploymentFileContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeploymentFileContentRequest.Merge(m, src)
}
func (m *QueryGetDeploymentFileContentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeploymentFileContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeploymentFileContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeploymentFileContentRequest proto.InternalMessageInfo

func (m *QueryGetDeploymentFileContentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryGetDeploymentFileContentRequest) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *QueryGetDeploymentFileContentRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ghostcloud.ghostcloud.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ghostcloud.ghostcloud.QueryParamsResponse")
	proto.RegisterType((*QueryGetDeploymentRequest)(nil), "ghostcloud.ghostcloud.QueryGetDeploymentRequest")
	proto.RegisterType((*QueryGetDeploymentResponse)(nil), "ghostcloud.ghostcloud.QueryGetDeploymentResponse")
	proto.RegisterType((*QueryAllDeploymentMetaRequest)(nil), "ghostcloud.ghostcloud.QueryAllDeploymentMetaRequest")
	proto.RegisterType((*QueryAllDeploymentMetaResponse)(nil), "ghostcloud.ghostcloud.QueryAllDeploymentMetaResponse")
	proto.RegisterType((*QueryDeploymentFileNamesRequest)(nil), "ghostcloud.ghostcloud.QueryDeploymentFileNamesRequest")
	proto.RegisterType((*QueryDeploymentFileNamesResponse)(nil), "ghostcloud.ghostcloud.QueryDeploymentFileNamesResponse")
	proto.RegisterType((*QueryGetDeploymentFileContentRequest)(nil), "ghostcloud.ghostcloud.QueryGetDeploymentFileContentRequest")
}

func init() { proto.RegisterFile("ghostcloud/ghostcloud/query.proto", fileDescriptor_1eaa93c58141bbd6) }

var fileDescriptor_1eaa93c58141bbd6 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0x77, 0x76, 0x11, 0xf0, 0x91, 0x98, 0x38, 0x40, 0x82, 0x8d, 0xdb, 0xc5, 0x46, 0x70,
	0x5d, 0x93, 0x56, 0x16, 0x94, 0x44, 0xe2, 0x81, 0x1f, 0x81, 0x70, 0xd0, 0x60, 0xf5, 0xc4, 0xc5,
	0x0c, 0xcb, 0x58, 0x37, 0x69, 0x3b, 0x65, 0x3b, 0x18, 0x08, 0xd9, 0x8b, 0x07, 0xcf, 0x26, 0xde,
	0xd5, 0x7f, 0x40, 0xe3, 0x5f, 0xe0, 0x99, 0x23, 0x46, 0x0f, 0x9e, 0x8c, 0x01, 0xff, 0x10, 0xd3,
	0x99, 0x59, 0xba, 0x0b, 0xfd, 0x01, 0xe2, 0x6d, 0xda, 0x7e, 0xdf, 0x7c, 0x3f, 0xef, 0xed, 0x7b,
	0x2f, 0x0b, 0x37, 0x9c, 0x97, 0x2c, 0xe4, 0x0d, 0x97, 0x6d, 0x6f, 0x5a, 0x5d, 0xc7, 0xad, 0x6d,
	0xda, 0xda, 0x35, 0x83, 0x16, 0xe3, 0x0c, 0x8f, 0xc6, 0xef, 0xcd, 0xf8, 0xa8, 0x8d, 0x38, 0xcc,
	0x61, 0x42, 0x61, 0x45, 0x27, 0x29, 0xd6, 0xae, 0x3b, 0x8c, 0x39, 0x2e, 0xb5, 0x48, 0xd0, 0xb4,
	0x88, 0xef, 0x33, 0x4e, 0x78, 0x93, 0xf9, 0xa1, 0xfa, 0x5a, 0x6b, 0xb0, 0xd0, 0x63, 0xa1, 0xb5,
	0x41, 0x42, 0x2a, 0x3d, 0xac, 0x57, 0x53, 0x1b, 0x94, 0x93, 0x29, 0x2b, 0x20, 0x4e, 0xd3, 0x17,
	0x62, 0xa5, 0xad, 0x26, 0x93, 0xbd, 0x68, 0xba, 0xf4, 0x79, 0x83, 0xf9, 0x9c, 0xfa, 0x5c, 0x29,
	0x27, 0x32, 0x94, 0x1e, 0xe5, 0x44, 0xc9, 0x8c, 0x64, 0x59, 0x40, 0x5a, 0xc4, 0xeb, 0x00, 0x4e,
	0x26, 0x6b, 0x36, 0x69, 0xe0, 0xb2, 0x5d, 0x2f, 0xb6, 0xbc, 0x93, 0xa7, 0xeb, 0x32, 0x36, 0x46,
	0x00, 0x3f, 0x89, 0x72, 0x5d, 0x13, 0x4e, 0x36, 0xdd, 0xda, 0xa6, 0x21, 0x37, 0x6c, 0x18, 0xee,
	0x79, 0x1b, 0x06, 0xcc, 0x0f, 0x29, 0x9e, 0x83, 0x7e, 0x49, 0x34, 0x86, 0xc6, 0x51, 0x75, 0xa8,
	0x5e, 0x36, 0x13, 0xcb, 0x6f, 0xca, 0xb0, 0x85, 0xbe, 0xfd, 0x5f, 0x95, 0x82, 0xad, 0x42, 0x8c,
	0x55, 0xb8, 0x26, 0xee, 0x5c, 0xa1, 0x7c, 0xe9, 0x18, 0x45, 0x19, 0xe2, 0x31, 0x18, 0x68, 0xb4,
	0x28, 0xe1, 0xac, 0x25, 0xae, 0xbe, 0x6c, 0x77, 0x1e, 0x31, 0x86, 0x3e, 0x9f, 0x78, 0x74, 0xac,
	0x28, 0x5e, 0x8b, 0xb3, 0xf1, 0x19, 0x81, 0x96, 0x74, 0x97, 0xc2, 0x7c, 0x0a, 0x57, 0xe2, 0x64,
	0x1f, 0x51, 0x4e, 0x14, 0xee, 0x44, 0x0a, 0xee, 0x52, 0x8f, 0x58, 0x61, 0x9f, 0xb8, 0x02, 0xcf,
	0xc1, 0x60, 0xf4, 0xa3, 0x89, 0xeb, 0x8a, 0xe3, 0xa5, 0xea, 0x50, 0xbd, 0x92, 0x72, 0xdd, 0xb2,
	0x92, 0xd9, 0xc7, 0x01, 0x86, 0x03, 0x65, 0xc1, 0x3b, 0xef, 0xba, 0xbd, 0x66, 0x9d, 0xfc, 0x97,
	0x01, 0xe2, 0x26, 0x53, 0xb8, 0x93, 0xa6, 0xec, 0x48, 0x33, 0xea, 0x48, 0x53, 0x76, 0xbd, 0xea,
	0x48, 0x73, 0x8d, 0x38, 0x54, 0xc5, 0xda, 0x5d, 0x91, 0xc6, 0x57, 0x04, 0x7a, 0x9a, 0x53, 0x46,
	0x75, 0x4a, 0x17, 0xad, 0xce, 0x4a, 0x0f, 0x7f, 0x51, 0xf0, 0xdf, 0xca, 0xe5, 0x97, 0x44, 0x3d,
	0x09, 0x7c, 0x40, 0x50, 0x11, 0x09, 0xc4, 0xb6, 0x51, 0x3d, 0x1f, 0x13, 0x8f, 0x86, 0xf9, 0xcd,
	0xa2, 0xc1, 0x60, 0xd8, 0xe4, 0x42, 0xad, 0x1a, 0xe6, 0xf8, 0xf9, 0x44, 0x89, 0x4b, 0xff, 0x5c,
	0xe2, 0x8f, 0x08, 0xc6, 0xd3, 0x09, 0x55, 0x91, 0xa7, 0xa1, 0xcf, 0x8b, 0x4b, 0x9b, 0xdb, 0x29,
	0x42, 0xfc, 0xff, 0x8a, 0xb8, 0x03, 0x37, 0x4f, 0x8f, 0x47, 0x64, 0xb6, 0x28, 0x77, 0xd3, 0xc5,
	0x0a, 0xa9, 0xc9, 0x49, 0x10, 0xdf, 0x4a, 0xf2, 0x5b, 0xe7, 0xb9, 0xfe, 0x7e, 0x00, 0x2e, 0x09,
	0x6b, 0xfc, 0x06, 0x41, 0xbf, 0xdc, 0x03, 0xf8, 0x76, 0x4a, 0xfa, 0xa7, 0x17, 0x8f, 0x56, 0x3b,
	0x8b, 0x54, 0x66, 0x6c, 0x4c, 0xbc, 0xfe, 0xfe, 0xe7, 0x5d, 0xb1, 0x82, 0xcb, 0x56, 0xd6, 0xf2,
	0xc4, 0x9f, 0x10, 0x40, 0x5c, 0x05, 0x7c, 0x37, 0xcb, 0x21, 0x69, 0x37, 0x69, 0x53, 0xe7, 0x88,
	0x50, 0x68, 0x0f, 0x04, 0xda, 0x0c, 0xae, 0x5b, 0x79, 0xbb, 0xd8, 0xda, 0x53, 0x25, 0x6f, 0x5b,
	0x7b, 0xd1, 0x6e, 0x6b, 0xe3, 0x2f, 0x08, 0xae, 0xf6, 0xce, 0xdc, 0xbc, 0xeb, 0xe2, 0x99, 0x2c,
	0x88, 0xb4, 0xb5, 0xa2, 0xdd, 0x3b, 0x67, 0x94, 0xc2, 0x37, 0x05, 0x7e, 0x15, 0x4f, 0xe6, 0xe3,
	0x8b, 0xc6, 0xfd, 0x86, 0x60, 0x38, 0x61, 0x1a, 0xf0, 0xfd, 0x2c, 0xfb, 0xf4, 0x01, 0xd7, 0x66,
	0xcf, 0x1d, 0xa7, 0xc0, 0x57, 0x05, 0xf8, 0x22, 0x9e, 0xcf, 0x07, 0x8f, 0x5a, 0x36, 0x14, 0xf8,
	0xdd, 0x3f, 0x41, 0xa7, 0xc9, 0xdb, 0xf8, 0x07, 0x82, 0xd1, 0xc4, 0xe1, 0xc1, 0x73, 0x67, 0xee,
	0x87, 0xd3, 0x23, 0xa7, 0x19, 0x19, 0xab, 0x40, 0x49, 0x8d, 0x75, 0x91, 0xc5, 0x33, 0x6c, 0x9f,
	0x35, 0x0b, 0xf5, 0x97, 0x23, 0x31, 0x11, 0x6b, 0xaf, 0x33, 0x9c, 0x0f, 0x6b, 0xb5, 0xf6, 0xc2,
	0xec, 0xfe, 0xa1, 0x8e, 0x0e, 0x0e, 0x75, 0xf4, 0xfb, 0x50, 0x47, 0x6f, 0x8f, 0xf4, 0xc2, 0xc1,
	0x91, 0x5e, 0xf8, 0x79, 0xa4, 0x17, 0xd6, 0xcb, 0x5d, 0x0e, 0x3b, 0xdd, 0x76, 0x7c, 0x37, 0xa0,
	0xe1, 0x46, 0xbf, 0xf8, 0xbf, 0x30, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x13, 0x21, 0x79, 0x7b,
	0x95, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	Deployment(ctx context.Context, in *QueryGetDeploymentRequest, opts ...grpc.CallOption) (*QueryGetDeploymentResponse, error)
	// Queries a list of all Deployment meta.
	DeploymentMetaAll(ctx context.Context, in *QueryAllDeploymentMetaRequest, opts ...grpc.CallOption) (*QueryAllDeploymentMetaResponse, error)
	DeploymentFileNames(ctx context.Context, in *QueryDeploymentFileNamesRequest, opts ...grpc.CallOption) (*QueryDeploymentFileNamesResponse, error)
	// Queries a deployment file content.
	DeploymentFileContent(ctx context.Context, in *QueryGetDeploymentFileContentRequest, opts ...grpc.CallOption) (*FileContent, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ghostcloud.ghostcloud.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Deployment(ctx context.Context, in *QueryGetDeploymentRequest, opts ...grpc.CallOption) (*QueryGetDeploymentResponse, error) {
	out := new(QueryGetDeploymentResponse)
	err := c.cc.Invoke(ctx, "/ghostcloud.ghostcloud.Query/Deployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DeploymentMetaAll(ctx context.Context, in *QueryAllDeploymentMetaRequest, opts ...grpc.CallOption) (*QueryAllDeploymentMetaResponse, error) {
	out := new(QueryAllDeploymentMetaResponse)
	err := c.cc.Invoke(ctx, "/ghostcloud.ghostcloud.Query/DeploymentMetaAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DeploymentFileNames(ctx context.Context, in *QueryDeploymentFileNamesRequest, opts ...grpc.CallOption) (*QueryDeploymentFileNamesResponse, error) {
	out := new(QueryDeploymentFileNamesResponse)
	err := c.cc.Invoke(ctx, "/ghostcloud.ghostcloud.Query/DeploymentFileNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DeploymentFileContent(ctx context.Context, in *QueryGetDeploymentFileContentRequest, opts ...grpc.CallOption) (*FileContent, error) {
	out := new(FileContent)
	err := c.cc.Invoke(ctx, "/ghostcloud.ghostcloud.Query/DeploymentFileContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	Deployment(context.Context, *QueryGetDeploymentRequest) (*QueryGetDeploymentResponse, error)
	// Queries a list of all Deployment meta.
	DeploymentMetaAll(context.Context, *QueryAllDeploymentMetaRequest) (*QueryAllDeploymentMetaResponse, error)
	DeploymentFileNames(context.Context, *QueryDeploymentFileNamesRequest) (*QueryDeploymentFileNamesResponse, error)
	// Queries a deployment file content.
	DeploymentFileContent(context.Context, *QueryGetDeploymentFileContentRequest) (*FileContent, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Deployment(ctx context.Context, req *QueryGetDeploymentRequest) (*QueryGetDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deployment not implemented")
}
func (*UnimplementedQueryServer) DeploymentMetaAll(ctx context.Context, req *QueryAllDeploymentMetaRequest) (*QueryAllDeploymentMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploymentMetaAll not implemented")
}
func (*UnimplementedQueryServer) DeploymentFileNames(ctx context.Context, req *QueryDeploymentFileNamesRequest) (*QueryDeploymentFileNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploymentFileNames not implemented")
}
func (*UnimplementedQueryServer) DeploymentFileContent(ctx context.Context, req *QueryGetDeploymentFileContentRequest) (*FileContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploymentFileContent not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostcloud.ghostcloud.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Deployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Deployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostcloud.ghostcloud.Query/Deployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Deployment(ctx, req.(*QueryGetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DeploymentMetaAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDeploymentMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DeploymentMetaAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostcloud.ghostcloud.Query/DeploymentMetaAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DeploymentMetaAll(ctx, req.(*QueryAllDeploymentMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DeploymentFileNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeploymentFileNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DeploymentFileNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostcloud.ghostcloud.Query/DeploymentFileNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DeploymentFileNames(ctx, req.(*QueryDeploymentFileNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DeploymentFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDeploymentFileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DeploymentFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostcloud.ghostcloud.Query/DeploymentFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DeploymentFileContent(ctx, req.(*QueryGetDeploymentFileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ghostcloud.ghostcloud.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Deployment",
			Handler:    _Query_Deployment_Handler,
		},
		{
			MethodName: "DeploymentMetaAll",
			Handler:    _Query_DeploymentMetaAll_Handler,
		},
		{
			MethodName: "DeploymentFileNames",
			Handler:    _Query_DeploymentFileNames_Handler,
		},
		{
			MethodName: "DeploymentFileContent",
			Handler:    _Query_DeploymentFileContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ghostcloud/ghostcloud/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDeploymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeploymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeploymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDeploymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeploymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeploymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FileMeta) > 0 {
		for iNdEx := len(m.FileMeta) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FileMeta[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.DeploymentMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDeploymentMetaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDeploymentMetaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDeploymentMetaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDeploymentMetaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDeploymentMetaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDeploymentMetaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DeploymentMeta) > 0 {
		for iNdEx := len(m.DeploymentMeta) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DeploymentMeta[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDeploymentFileNamesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDeploymentFileNamesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDeploymentFileNamesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SiteName) > 0 {
		i -= len(m.SiteName)
		copy(dAtA[i:], m.SiteName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SiteName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDeploymentFileNamesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDeploymentFileNamesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDeploymentFileNamesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Meta) > 0 {
		for iNdEx := len(m.Meta) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Meta[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDeploymentFileContentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeploymentFileContentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeploymentFileContentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FileName) > 0 {
		i -= len(m.FileName)
		copy(dAtA[i:], m.FileName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FileName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SiteName) > 0 {
		i -= len(m.SiteName)
		copy(dAtA[i:], m.SiteName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SiteName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDeploymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDeploymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DeploymentMeta.Size()
	n += 1 + l + sovQuery(uint64(l))
	if len(m.FileMeta) > 0 {
		for _, e := range m.FileMeta {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAllDeploymentMetaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDeploymentMetaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DeploymentMeta) > 0 {
		for _, e := range m.DeploymentMeta {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDeploymentFileNamesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SiteName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDeploymentFileNamesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Meta) > 0 {
		for _, e := range m.Meta {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDeploymentFileContentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SiteName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.FileName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeploymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeploymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeploymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeploymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeploymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeploymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeploymentMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DeploymentMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileMeta = append(m.FileMeta, &FileMeta{})
			if err := m.FileMeta[len(m.FileMeta)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDeploymentMetaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDeploymentMetaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDeploymentMetaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDeploymentMetaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDeploymentMetaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDeploymentMetaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeploymentMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeploymentMeta = append(m.DeploymentMeta, DeploymentMeta{})
			if err := m.DeploymentMeta[len(m.DeploymentMeta)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDeploymentFileNamesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDeploymentFileNamesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDeploymentFileNamesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SiteName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SiteName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDeploymentFileNamesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDeploymentFileNamesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDeploymentFileNamesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meta = append(m.Meta, &FileMeta{})
			if err := m.Meta[len(m.Meta)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeploymentFileContentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeploymentFileContentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeploymentFileContentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SiteName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SiteName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
